#!/usr/bin/env bash

OPL=woody-opl    # use -DOPLTYPE_IS_OPL3 (needs OPL3)
#OPL=Nuked-OPL3  # use -DOPL_NUKED

clang -g -Wall -DNORMALUNIX=1 -DOPLTYPE_IS_OPL3 \
  -I../platform -I../thirdparty/musplayer \
  -I../thirdparty/$OPL \
  -I /opt/homebrew/Cellar/sdl2/2.32.0/include \
  -L /opt/homebrew/Cellar/sdl2/2.32.0/lib \
  -l SDL2 \
  *.c \
  ../platform/*.c \
  ../thirdparty/musplayer/*.c \
  ../thirdparty/$OPL/*.c \
  -o ../doom
